Feature/burbano dawson
JLESC/jlesc.github.io pull request #367
Opened 2017-12-13 09:21 UTC by william-dawson

I have added a description of the collaboration between Mario Burbano and myself. I also added Mario to the list of people in the data directory.

2017-12-13 09:31 UTC, pancetta requested changes
Well done! Nice to see someone doing this procedure without bazillion mehmehmeh-emails.. only minor comments/questions, see below.

2017-12-13 09:31 UTC, pancetta commented on _projects/ewald_matrix.md
> +  - numerics
Doesn't this fit into applications as well?

2017-12-13 09:31 UTC, pancetta commented on _projects/ewald_matrix.md
> +{% bibliography --file external/ewald_matrix %}
Could you cite the reference somewhere in the text?

2017-12-13 11:43 UTC, pancetta commented on _projects/ewald_matrix.md
> +status: running
Is it really running or is it starting?

2017-12-14 03:42 UTC, william-dawson commented
Thanks for the feedback Robert, I've made modifications in accordance to your suggestions. Let me know if there is anything else you recommend!

2017-12-14 06:46 UTC, merged

2017-12-14 06:46 UTC, pancetta commented
Nope, all good! Thanks!